### ISSUE TITLE
sendto error

### ISSUE THREAD

**Issue by dgjustice** [facebook/fbtracert#16]
This may be a *nix noob question.  I've tried installing the package on ubuntu 16 with the same results.  I'm getting the following error on both:

```
E0403 22:40:26.868879   25840 main.go:368] Error sending packet write ip4 y.y.y.y->x.x.x.x: sendto: operation not permitted
```

Is this an error in code, or possibly a NIC configuration I am missing on my end?  I am running the command as root.

```
~/projects# ./bin/fbtracert x.x.x.x
```

**Comment by coxley** [comment]
Interesting...

`$EUID` is definitely `0`?

**Comment by dgjustice** [comment]
```
# echo $EUID
0
root@myserver:~# cat /etc/issue
Ubuntu 16.04.1 LTS \n \l
```
I tried with the repo default golang of 1.6.2 as well as 1.8 from the official site with the same result.

**Comment by nemith** [comment]
I wonder if this is appamour getting involved.

Is there any app amour logs in dmesg or anything that pops up with aa_logprof?

**Comment by dgjustice** [comment]
```
 /etc/init.d/apparmor teardown
 * Unloading AppArmor profiles                                                                                 [ OK ]
root@
```

I unloaded it and stopped the service.  Nothing has been logged to dmesg or syslog that I can see (even before doing that).  Any chance I need to mess with one of the net sysclt knobs?

**Comment by dgjustice** [comment]
I'm going to close this.  Digging into it further, I agree that it points towards apparmor settings.  I'm going to try a different box/OS when I have time.  This seems to be an isolated [my] issue.  Thanks for the help!

**Comment by coxley** [comment]
No worries, good luck!

**Comment by haojunsheng** [comment]
I also have this question, anyone can help me?
