### ISSUE TITLE
IPv4 responses discarded for packet being too short

### ISSUE THREAD

**Issue by boilersam** [facebook/fbtracert#21]
Running on CentOS7 VM using IPv4, the received packet count is 0.  Looks like TCPReceiver makes a wrong assumption on the packet containing the IP header.  Setting ipHdrSize to 0 allows the packets to be processed.

$ sudo  ./fbtracert -v 4 -showAll -logtostderr=true  -maxTTL 10 -maxSrcPorts 32 10.0.2.3
Using as source address: 10.0.2.15
Starting fbtracert with 96 probes per second/ttl, base src port 32768 and with the port span of 32
I0111 11:56:19.841790    4879 main.go:317] Sender for ttl 1 starting
I0111 11:56:19.845808    4879 main.go:317] Sender for ttl 2 starting
I0111 11:56:19.848624    4879 main.go:317] Sender for ttl 3 starting
I0111 11:56:19.851057    4879 main.go:317] Sender for ttl 4 starting
I0111 11:56:19.853162    4879 main.go:317] Sender for ttl 5 starting
I0111 11:56:19.876749    4879 main.go:317] Sender for ttl 6 starting
I0111 11:56:19.881893    4879 main.go:317] Sender for ttl 7 starting
I0111 11:56:19.884557    4879 main.go:317] Sender for ttl 8 starting
I0111 11:56:19.887251    4879 main.go:317] Sender for ttl 9 starting
I0111 11:56:19.890524    4879 main.go:317] Sender for ttl 10 starting
I0111 11:56:19.893032    4879 main.go:230] ICMPReceiver is starting...
I0111 11:56:19.897605    4879 main.go:116] TCPReceiver starting...
I0111 11:57:21.580310    4879 main.go:386] Sender done
I0111 11:57:21.581231    4879 main.go:386] Sender done
I0111 11:57:21.581571    4879 main.go:386] Sender done
I0111 11:57:21.581655    4879 main.go:386] Sender done
I0111 11:57:21.590584    4879 main.go:386] Sender done
I0111 11:57:21.591154    4879 main.go:386] Sender done
I0111 11:57:21.598758    4879 main.go:386] Sender done
I0111 11:57:21.598863    4879 main.go:386] Sender done
I0111 11:57:21.598914    4879 main.go:386] Sender done
I0111 11:57:21.598963    4879 main.go:386] Sender done
I0111 11:57:21.599070    4879 main.go:614] All senders finished!
I0111 11:57:23.599694    4879 main.go:274] ICMPReceiver done
I0111 11:57:23.599761    4879 main.go:195] TCPReceiver terminating...
+-----+-------------+-----------+-------------+-----------+-------------+-----------+-------------+-----------+
| TTL | PORT: 32774 | SENT/RCVD | PORT: 32789 | SENT/RCVD | PORT: 32790 | SENT/RCVD | PORT: 32794 | SENT/RCVD |
+-----+-------------+-----------+-------------+-----------+-------------+-----------+-------------+-----------+
|   1 | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    |
|   2 | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    |
|   3 | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    |
|   4 | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    |
|   5 | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    |
|   6 | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    |
|   7 | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    |
|   8 | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    |
|   9 | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    |
|  10 | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    | ?           | 180/00    |
+-----+-------------+-----------+-------------+-----------+-------------+-----------+-------------+-----------+
...
`
*************** func TCPReceiver(done <-chan struct{}, a
*** 130,135 ****
--- 130,137 ----
                if af == "ip4" {
                        // IPv4 header is always included with the ipv4 raw socket receive
                        ipHdrSize = minIP4HeaderSize
+                       // By the time the packet gets here it is at the source port
+                       ipHdrSize = 0
                }
                packet := make([]byte, ipHdrSize+maxTCPHdrSize)
`

**Comment by purushothamanr** [comment]
@boilersam  Since you are trying your command from your local VM, you are getting the RCVD count as "0" for all the request that is been sent out.

Can you check whether you are able to **PING the hose 10.0.2.3"** before issuing the command **sudo ./fbtracert -v 4 -showAll -logtostderr=true -maxTTL 10 -maxSrcPorts 32 10.0.2.3**?

If the ping is successful we can check why you are getting "0" as the RCVD count. But if the ping says "Host Unreachable" then you need to provide the valid host IP.

Regards,
Purushoth

**Comment by boilersam** [comment]
Hi Purushoth,
Thanks for getting back to me.  Ping to 10.0.2.3 is working fine, but regular traceroute is not.  I have a few interfaces on this VM and the one with 10.0.2.0/24 looks like I have  set up for NAT in VirtualBox.  If I switch to an IP address for another VM on a bridged network, fbtracert is getting responses.

```
[root@localhost ~]# fbtracert -v 3 -showAll -logtostderr=true -maxTTL 10 -maxSrcPorts 32 10.5.5.1
Using as source address: 10.5.5.4
Starting fbtracert with 96 probes per second/ttl, base src port 32768 and with the port span of 32
I0223 09:11:58.877859    6529 main.go:321] Sender for ttl 1 starting
I0223 09:11:58.878416    6529 main.go:321] Sender for ttl 2 starting
I0223 09:11:58.878452    6529 main.go:321] Sender for ttl 3 starting
I0223 09:11:58.878476    6529 main.go:321] Sender for ttl 4 starting
I0223 09:11:58.878498    6529 main.go:321] Sender for ttl 5 starting
I0223 09:11:58.878518    6529 main.go:321] Sender for ttl 6 starting
I0223 09:11:58.878540    6529 main.go:321] Sender for ttl 7 starting
I0223 09:11:58.878560    6529 main.go:321] Sender for ttl 8 starting
I0223 09:11:58.878579    6529 main.go:321] Sender for ttl 9 starting
I0223 09:11:58.878607    6529 main.go:321] Sender for ttl 10 starting
I0223 09:11:58.878650    6529 main.go:234] ICMPReceiver is starting...
I0223 09:11:58.878659    6529 main.go:116] TCPReceiver starting...
I0223 09:11:58.879913    6529 main.go:386] Sender for ttl 10 exiting prematurely 
I0223 09:11:58.880292    6529 main.go:386] Sender for ttl 2 exiting prematurely  
I0223 09:11:58.880307    6529 main.go:386] Sender for ttl 3 exiting prematurely  
I0223 09:11:58.880324    6529 main.go:386] Sender for ttl 7 exiting prematurely  
I0223 09:11:58.891262    6529 main.go:386] Sender for ttl 9 exiting prematurely  
I0223 09:11:58.891427    6529 main.go:386] Sender for ttl 4 exiting prematurely  
I0223 09:11:58.891579    6529 main.go:386] Sender for ttl 8 exiting prematurely  
I0223 09:11:58.906891    6529 main.go:386] Sender for ttl 6 exiting prematurely  
I0223 09:11:58.917916    6529 main.go:386] Sender for ttl 5 exiting prematurely  
I0223 09:13:01.016822    6529 main.go:390] Sender done
I0223 09:13:01.017508    6529 main.go:618] All senders finished!
I0223 09:13:03.018186    6529 main.go:278] ICMPReceiver done
I0223 09:13:03.018251    6529 main.go:199] TCPReceiver terminating...
+-----+-------------+-----------+-------------+-----------+-------------+-----------+-------------+-----------+
| TTL | PORT: 32799 | SENT/RCVD | PORT: 32796 | SENT/RCVD | PORT: 32797 | SENT/RCVD | PORT: 32788 | SENT/RCVD |
+-----+-------------+-----------+-------------+-----------+-------------+-----------+-------------+-----------+
|   1 | 10.5.5.1    | 180/180   | 10.5.5.1    | 180/180   | 10.5.5.1    | 180/180   | 10.5.5.1    | 180/180   |
+-----+-------------+-----------+-------------+-----------+-------------+-----------+-------------+-----------+
...
+-----+-------------+-----------+-------------+-----------+-------------+-----------+-------------+-----------+
| TTL | PORT: 32773 | SENT/RCVD | PORT: 32790 | SENT/RCVD | PORT: 32784 | SENT/RCVD | PORT: 32770 | SENT/RCVD |
+-----+-------------+-----------+-------------+-----------+-------------+-----------+-------------+-----------+
|   1 | 10.5.5.1    | 180/180   | 10.5.5.1    | 180/180   | 10.5.5.1    | 180/180   | 10.5.5.1    | 180/179   |
+-----+-------------+-----------+-------------+-----------+-------------+-----------+-------------+-----------+
```
