### ISSUE TITLE
Compilation error on windows 8

### ISSUE THREAD

**Issue by zanzamer** [facebook/fbtracert#7]
using latast golang v1.6.3 on windows 8 x64:

![image](https://cloud.githubusercontent.com/assets/21025412/17650856/0e46ba4a-6261-11e6-8d48-c3605712c7e3.png)

**Comment by coxley** [comment]
@zanzamer Sorry that this took so long, but another contributor was gracious enough to help us handle sockets more generically. This should allow for it working on windows, with the exceptions noted in this PR: #10
